# Generated by Django 5.2.4 on 2025-08-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_donatedresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatedresource',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donatedresource',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
