# Generated by Django 5.2.4 on 2025-08-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_donatedresource_latitude_donatedresource_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidrequest',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donatedresource',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
