name: LocalAid Backend Tests & Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-django pytest-cov

    - name: Set environment variables
      run: |
        echo "DJANGO_SETTINGS_MODULE=localaid_project.settings" >> $GITHUB_ENV

    - name: Run Django migrations
      run: |
        python manage.py migrate

    - name: Run tests with coverage
      run: |
        pytest --cov=core --cov=accounts --cov-report=term-missing --cov-report=xml
